management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
    pool:
      enabled: true
    in-memory: false
  jms:
    listener:
      max-concurrency: 5
