version: '3.7'

networks:
  overlay-net:

volumes:
  appdynamics-agent-vol:
  activemq-data:
  activemq-log:

services:
  activemq:
    image: webcenter/activemq:latest
    restart: always
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    volumes:
      - activemq-data:/data/activemq
      - activemq-log:/var/log/activemq
    networks:
      - overlay-net

  appdynamics-agent:
    image: nkavtur/java-appd-agent:latest
    volumes:
      - appdynamics-agent-vol:/sharedFiles

  backend-app:
    image: nkavtur/micrometer-app:latest
    restart: always
    ports:
      - "8080:8080"
      - "9010:9010"
    volumes:
      - appdynamics-agent-vol:/sharedFiles
    networks:
    - overlay-net
    environment:
      - APPDYNAMICS_CONTROLLER_HOST_NAME=grace201901100005489.saas.appdynamics.com
      - APPDYNAMICS_CONTROLLER_PORT=443
      - APPDYNAMICS_CONTROLLER_SSL_ENABLED=true
      - APPDYNAMICS_AGENT_APPLICATION_NAME=backend-app
      - APPDYNAMICS_AGENT_TIER_NAME=backend-tier
      - APPDYNAMICS_AGENT_NODE_NAME=backend-node
