version: '3.4'

networks:
  overlay-net:

volumes:
  appdynamics-agent-vol:
  activemq-data:
  activemq-log:

services:
  activemq:
    image: webcenter/activemq:latest
    restart: always
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    volumes:
      - activemq-data:/data/activemq
      - activemq-log:/var/log/activemq
    networks:
      - overlay-net

  appdynamics-agent:
    image: nkavtur/java-appd-agent:latest
    volumes:
      - appdynamics-agent-vol:/sharedFiles

  backend-app:
    image: nkavtur/users-backend-app:latest
    restart: always
    ports:
      - "8080:8080"
      - "9010:9010"
    volumes:
      - appdynamics-agent-vol:/sharedFiles
    networks:
    - overlay-net
    environment:
      - APPDYNAMICS_CONTROLLER_HOST_NAME=${APPDYNAMICS_CONTROLLER_HOST_NAME}
      - APPDYNAMICS_CONTROLLER_PORT=443
      - APPDYNAMICS_CONTROLLER_SSL_ENABLED=true
      - APPDYNAMICS_AGENT_APPLICATION_NAME=backend-app
      - APPDYNAMICS_AGENT_TIER_NAME=backend-tier
      - APPDYNAMICS_AGENT_NODE_NAME=backend-node
      - APPDYNAMICS_AGENT_ACCOUNT_NAME=${APPDYNAMICS_AGENT_ACCOUNT_NAME}
      - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
      - JAVA_OPTS=-Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=0.0.0.0 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false

  gateway-app:
    image: nkavtur/users-gateway-app:latest
    restart: always
    ports:
      - "8888:8888"
      - "9011:9011"
    volumes:
      - appdynamics-agent-vol:/sharedFiles
    networks:
      - overlay-net
    environment:
      - APPDYNAMICS_CONTROLLER_HOST_NAME=${APPDYNAMICS_CONTROLLER_HOST_NAME}
      - APPDYNAMICS_CONTROLLER_PORT=443
      - APPDYNAMICS_CONTROLLER_SSL_ENABLED=true
      - APPDYNAMICS_AGENT_APPLICATION_NAME=gateway-app
      - APPDYNAMICS_AGENT_TIER_NAME=backend-tier
      - APPDYNAMICS_AGENT_NODE_NAME=backend-node
      - APPDYNAMICS_AGENT_ACCOUNT_NAME=${APPDYNAMICS_AGENT_ACCOUNT_NAME}
      - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
      - JAVA_OPTS=-Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=0.0.0.0 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9011 -Dcom.sun.management.jmxremote.port=9011 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
